//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSIU_API.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public long Id { get; set; }
        public string Data { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public long MessageId { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
